apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefunctions-deployment
spec:
  selector:
    matchLabels:
      app: kubefunctions-pod
  template:
    metadata:
      labels:
        app: kubefunctions-pod
    spec:
      containers:
        - name: kubefunctions-container
          image: ghcr.io/arkapravasinha/kubefunctions:v1.0.4-PullRequest0002.3
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 80
